# Generated by Django 5.0.1 on 2024-03-14 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='user_has_voted',
            field=models.BooleanField(default=False),
        ),
    ]
